from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Any, Literal

from app.models import ToolResult
from app.office_artifacts import latest_summary_path
from app.presentation_config import presentation_config

OUTLOOK_MAIL_ITEM = 0


def outlook_draft_status() -> dict[str, Any]:
    registered = False
    clsid: str | None = None
    if os.name == "nt":
        try:
            import winreg

            with winreg.OpenKey(
                winreg.HKEY_CLASSES_ROOT,
                r"Outlook.Application\CLSID",
            ) as key:
                clsid = str(winreg.QueryValueEx(key, None)[0])
                registered = bool(clsid)
        except OSError:
            registered = False

    sender = presentation_config.outlook_sender_email
    recipient = presentation_config.recipient_email
    addresses_are_distinct = sender.casefold() != recipient.casefold()
    return {
        "provider": "classic_outlook_com",
        "outlook_com_registered": registered,
        "outlook_application_clsid": clsid,
        "outlook_draft_configured": registered and addresses_are_distinct,
        "sender_account_email": sender,
        "recipient_name": presentation_config.recipient_name,
        "recipient_email": recipient,
        "sender_recipient_distinct": addresses_are_distinct,
        "email_send_enabled": False,
    }


def _clean_subject(subject: str | None, language: Literal["zh", "en"]) -> str:
    clean = " ".join((subject or "").split())[:180]
    if clean:
        return clean
    return (
        "演示摘要：Loss.pptx"
        if language == "zh"
        else "Presentation summary: Loss.pptx"
    )


def _message_body(
    summary_text: str,
    language: Literal["zh", "en"],
) -> str:
    if language == "zh":
        return (
            f"{presentation_config.recipient_name}，您好：\n\n"
            "以下是 Smart Office Agent 生成的演示摘要。"
            "该邮件目前仅保存为 Outlook 草稿，尚未发送。\n\n"
            f"{summary_text}"
        )
    return (
        f"Hello {presentation_config.recipient_name},\n\n"
        "Below is the presentation summary generated by Smart Office Agent. "
        "This message has only been saved as an Outlook draft and has not been sent.\n\n"
        f"{summary_text}"
    )


def _outlook_application(win32_client: Any) -> tuple[Any, str]:
    try:
        return win32_client.GetActiveObject("Outlook.Application"), "active_object"
    except Exception:
        return win32_client.Dispatch("Outlook.Application"), "dispatch"


def _account_email(account: Any) -> str:
    if account is None:
        return ""
    for attribute in ("SmtpAddress", "UserName", "DisplayName"):
        try:
            value = str(getattr(account, attribute, "") or "").strip()
        except Exception:
            value = ""
        if "@" in value:
            return value
    return ""


def _find_sender_account(namespace: Any, expected_email: str) -> tuple[Any, list[str]]:
    accounts = namespace.Accounts
    detected: list[str] = []
    match = None
    for index in range(1, int(accounts.Count) + 1):
        account = accounts.Item(index)
        address = _account_email(account)
        if address:
            detected.append(address)
        if address.casefold() == expected_email.casefold():
            match = account
    if match is None:
        visible = ", ".join(detected) if detected else "none"
        raise RuntimeError(
            f"Configured Outlook sender account was not found: {expected_email}. "
            f"Detected accounts: {visible}."
        )
    return match, detected


def create_outlook_summary_draft(
    *,
    language: Literal["zh", "en"] = "zh",
    subject: str | None = None,
    display: bool = True,
) -> ToolResult:
    summary_path = latest_summary_path()
    if summary_path is None or not summary_path.is_file():
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=False,
            message="No generated presentation summary is available for the Outlook draft.",
            data={
                "execution_mode": "failed",
                "requested_state": {"outlook_draft_created": True},
                "email_send_enabled": False,
                "sent": False,
            },
        )

    sender_email = presentation_config.outlook_sender_email.strip()
    recipient_email = presentation_config.recipient_email.strip()
    if not sender_email or not recipient_email:
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=False,
            message="Outlook sender and recipient email addresses must both be configured.",
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "failed",
                "requested_state": {"outlook_draft_created": True},
                "sender_account_email": sender_email,
                "recipient_email": recipient_email,
                "email_send_enabled": False,
                "sent": False,
            },
        )
    if sender_email.casefold() == recipient_email.casefold():
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=False,
            message="Outlook sender and recipient must be different email addresses.",
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "failed",
                "requested_state": {"outlook_draft_created": True},
                "sender_account_email": sender_email,
                "recipient_email": recipient_email,
                "email_send_enabled": False,
                "sent": False,
            },
        )

    if os.name != "nt":
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=False,
            message="Classic Outlook COM automation is available only on Windows.",
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "failed",
                "requested_state": {"outlook_draft_created": True},
                "summary_path": str(summary_path),
                "sender_account_email": sender_email,
                "recipient_email": recipient_email,
                "email_send_enabled": False,
                "sent": False,
            },
        )

    try:
        import pythoncom
        import win32com.client
    except ImportError as exc:
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=False,
            message="pywin32 is required for Classic Outlook draft creation.",
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "failed",
                "requested_state": {"outlook_draft_created": True},
                "summary_path": str(summary_path),
                "sender_account_email": sender_email,
                "recipient_email": recipient_email,
                "email_send_enabled": False,
                "sent": False,
                "error": f"{type(exc).__name__}: {exc}",
            },
        )

    pythoncom.CoInitialize()
    try:
        outlook, connection_mode = _outlook_application(win32com.client)
        namespace = outlook.GetNamespace("MAPI")
        sender_account, detected_accounts = _find_sender_account(namespace, sender_email)
        summary_text = summary_path.read_text(encoding="utf-8")
        clean_subject = _clean_subject(subject, language)

        mail = outlook.CreateItem(OUTLOOK_MAIL_ITEM)
        mail.SendUsingAccount = sender_account
        assigned_sender = _account_email(getattr(mail, "SendUsingAccount", None))
        if assigned_sender.casefold() != sender_email.casefold():
            raise RuntimeError(
                f"Outlook did not bind the draft to the configured sender account {sender_email}."
            )

        mail.To = recipient_email
        mail.Subject = clean_subject
        mail.Body = _message_body(summary_text, language)
        mail.Save()
        time.sleep(0.15)

        entry_id = str(getattr(mail, "EntryID", "") or "")
        store_id = ""
        parent = getattr(mail, "Parent", None)
        if parent is not None:
            store_id = str(getattr(parent, "StoreID", "") or "")

        if not entry_id:
            raise RuntimeError("Outlook saved the draft but did not assign an EntryID.")

        saved = (
            namespace.GetItemFromID(entry_id, store_id)
            if store_id
            else namespace.GetItemFromID(entry_id)
        )
        saved_entry_id = str(getattr(saved, "EntryID", "") or "")
        saved_subject = str(getattr(saved, "Subject", "") or "")
        saved_to = str(getattr(saved, "To", "") or "")
        saved_sender = _account_email(getattr(saved, "SendUsingAccount", None))
        saved_state = bool(getattr(saved, "Saved", False))
        sent_state = bool(getattr(saved, "Sent", False))

        verified = bool(
            saved_entry_id == entry_id
            and saved_subject == clean_subject
            and recipient_email.casefold() in saved_to.casefold()
            and saved_sender.casefold() == sender_email.casefold()
            and saved_state
            and not sent_state
        )
        if not verified:
            raise RuntimeError(
                "The Outlook draft was created but sender, recipient, saved state, or unsent state could not be verified."
            )

        displayed = False
        if display:
            saved.Display(False)
            displayed = True

        relative_summary = _relative_or_absolute(summary_path)
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=True,
            message=(
                f"Outlook draft created from {sender_email} for {recipient_email}; "
                "it was not sent."
            ),
            expected_process_names=["OUTLOOK.EXE"],
            expected_window_keywords=[clean_subject, "Outlook"],
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "real",
                "requested_state": {"outlook_draft_created": True},
                "outlook_draft_created": True,
                "outlook_draft_verified": True,
                "outlook_draft_entry_id": entry_id,
                "outlook_draft_store_id": store_id,
                "outlook_draft_displayed": displayed,
                "outlook_connection_mode": connection_mode,
                "sender_account_email": sender_email,
                "detected_outlook_accounts": detected_accounts,
                "recipient_name": presentation_config.recipient_name,
                "recipient_email": recipient_email,
                "subject": clean_subject,
                "summary_path": str(summary_path),
                "summary_path_relative": relative_summary,
                "email_send_enabled": False,
                "sent": False,
            },
            raw={
                "outlook_draft_entry_id": entry_id,
                "outlook_draft_verified": True,
                "sender_account_email": sender_email,
                "recipient_email": recipient_email,
                "email_send_enabled": False,
                "sent": False,
            },
        )
    except Exception as exc:
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=False,
            message=f"Outlook draft could not be created: {type(exc).__name__}: {exc}",
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "failed",
                "requested_state": {"outlook_draft_created": True},
                "summary_path": str(summary_path),
                "summary_path_relative": _relative_or_absolute(summary_path),
                "sender_account_email": sender_email,
                "recipient_email": recipient_email,
                "email_send_enabled": False,
                "sent": False,
                "error": f"{type(exc).__name__}: {exc}",
            },
        )
    finally:
        pythoncom.CoUninitialize()


def _relative_or_absolute(path: Path) -> str:
    from app.presentation_config import REPO_ROOT

    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path.resolve())
