from __future__ import annotations

import logging
import os
import time
from pathlib import Path
from typing import Any, Literal

from app.models import ToolResult
from app.office_artifacts import latest_summary_path
from app.presentation_config import EmailRecipient, presentation_config

LOGGER = logging.getLogger(__name__)

OUTLOOK_MAIL_ITEM = 0
OUTLOOK_TO_RECIPIENT = 1
PR_SMTP_ADDRESS = "http://schemas.microsoft.com/mapi/proptag/0x39FE001E"


def outlook_draft_status() -> dict[str, Any]:
    registered = False
    clsid: str | None = None
    if os.name == "nt":
        try:
            import winreg

            with winreg.OpenKey(
                winreg.HKEY_CLASSES_ROOT,
                r"Outlook.Application\CLSID",
            ) as key:
                clsid = str(winreg.QueryValueEx(key, None)[0])
                registered = bool(clsid)
        except OSError:
            registered = False

    sender = presentation_config.outlook_sender_email.strip()
    try:
        directory = presentation_config.recipient_directory()
        default_recipient = directory.resolve()
        catalog = directory.public_catalog()
        config_error = None
    except (OSError, ValueError) as exc:
        default_recipient = None
        catalog = []
        config_error = str(exc)

    addresses_are_distinct = bool(catalog) and all(
        sender.casefold() != recipient["email"].casefold() for recipient in catalog
    )
    return {
        "provider": "classic_outlook_com",
        "outlook_com_registered": registered,
        "outlook_application_clsid": clsid,
        "outlook_draft_configured": (
            registered and addresses_are_distinct and default_recipient is not None
        ),
        "sender_account_email": sender,
        "recipient_config_path": str(presentation_config.recipient_config_path),
        "recipient_config_exists": presentation_config.recipient_config_path.is_file(),
        "recipient_config_error": config_error,
        "recipient_file_hot_reload_enabled": True,
        "default_recipient_key": default_recipient.key if default_recipient else None,
        "recipient_key": default_recipient.key if default_recipient else None,
        "recipient_name": default_recipient.name if default_recipient else None,
        "recipient_email": default_recipient.email if default_recipient else None,
        "recipient_catalog": catalog,
        "allowed_recipient_keys": [recipient["key"] for recipient in catalog],
        "sender_recipient_distinct": addresses_are_distinct,
        "email_send_enabled": False,
        "approval_gated_email_send_enabled": True,
        "unrestricted_email_send_enabled": False,
    }


def _clean_subject(subject: str | None, language: Literal["zh", "en"]) -> str:
    clean = " ".join((subject or "").split())[:180]
    if clean:
        return clean
    return "演示摘要：Loss.pptx" if language == "zh" else "Presentation summary: Loss.pptx"


def _message_body(
    summary_text: str,
    language: Literal["zh", "en"],
    recipient_name: str,
) -> str:
    if language == "zh":
        return (
            f"{recipient_name}，您好：\n\n"
            "以下是 Smart Office Agent 生成的演示摘要。"
            "该邮件目前仅保存为 Outlook 草稿，尚未发送。\n\n"
            f"{summary_text}"
        )
    return (
        f"Hello {recipient_name},\n\n"
        "Below is the presentation summary generated by Smart Office Agent. "
        "This message has only been saved as an Outlook draft and has not been sent.\n\n"
        f"{summary_text}"
    )


def _outlook_application(win32_client: Any) -> tuple[Any, str]:
    try:
        return win32_client.GetActiveObject("Outlook.Application"), "active_object"
    except Exception:
        return win32_client.Dispatch("Outlook.Application"), "dispatch"


def _account_email(account: Any) -> str:
    if account is None:
        return ""
    for attribute in ("SmtpAddress", "UserName", "DisplayName"):
        try:
            value = str(getattr(account, attribute, "") or "").strip()
        except Exception:
            value = ""
        if "@" in value:
            return value
    return ""


def _find_sender_account(namespace: Any, expected_email: str) -> tuple[Any, list[str]]:
    accounts = namespace.Accounts
    detected: list[str] = []
    match = None
    for index in range(1, int(accounts.Count) + 1):
        account = accounts.Item(index)
        address = _account_email(account)
        if address:
            detected.append(address)
        if address.casefold() == expected_email.casefold():
            match = account
    if match is None:
        visible = ", ".join(detected) if detected else "none"
        raise RuntimeError(
            f"Configured Outlook sender account was not found: {expected_email}. "
            f"Detected accounts: {visible}."
        )
    return match, detected


def _recipient_smtp_address(recipient: Any) -> str:
    try:
        value = str(recipient.PropertyAccessor.GetProperty(PR_SMTP_ADDRESS) or "").strip()
        if value:
            return value
    except Exception:
        pass

    try:
        entry = recipient.AddressEntry
        entry_type = str(getattr(entry, "Type", "") or "").upper()
        if entry_type == "EX":
            exchange_user = entry.GetExchangeUser()
            value = str(getattr(exchange_user, "PrimarySmtpAddress", "") or "").strip()
            if value:
                return value
        value = str(getattr(entry, "Address", "") or "").strip()
        if value:
            return value
    except Exception:
        pass

    try:
        return str(getattr(recipient, "Address", "") or "").strip()
    except Exception:
        return ""


def _recipient_smtp_addresses(mail: Any) -> list[str]:
    recipients = mail.Recipients
    addresses: list[str] = []
    for index in range(1, int(recipients.Count) + 1):
        value = _recipient_smtp_address(recipients.Item(index))
        if value:
            addresses.append(value)
    return addresses


def _exception_details(exc: Exception) -> dict[str, Any]:
    return {
        "error_type": type(exc).__name__,
        "error": str(exc),
        "hresult": getattr(exc, "hresult", None),
        "args": repr(getattr(exc, "args", ())),
    }


def _failed_result(
    *,
    message: str,
    summary_path: Path | None,
    sender_email: str,
    recipient: EmailRecipient | None,
    requested_recipient_key: str | None,
    stage: str,
    detected_accounts: list[str] | None = None,
    entry_id: str = "",
    exc: Exception | None = None,
) -> ToolResult:
    details: dict[str, Any] = {
        "execution_mode": "failed",
        "requested_state": {
            "outlook_draft_created": True,
            "recipient_key": requested_recipient_key,
        },
        "summary_path": str(summary_path) if summary_path else None,
        "summary_path_relative": _relative_or_absolute(summary_path) if summary_path else None,
        "sender_account_email": sender_email,
        "recipient_key": recipient.key if recipient else requested_recipient_key,
        "recipient_name": recipient.name if recipient else None,
        "recipient_email": recipient.email if recipient else None,
        "failure_stage": stage,
        "detected_outlook_accounts": detected_accounts or [],
        "outlook_draft_entry_id": entry_id or None,
        "recipient_config_path": str(presentation_config.recipient_config_path),
        "email_send_enabled": False,
        "approval_gated_email_send_enabled": True,
        "unrestricted_email_send_enabled": False,
        "sent": False,
    }
    if exc is not None:
        details.update(_exception_details(exc))

    LOGGER.error(
        "OUTLOOK_DRAFT_FAILURE stage=%s sender=%s recipient_key=%s recipient=%s detected_accounts=%s entry_id=%s error_type=%s error=%s hresult=%s args=%s",
        stage,
        sender_email,
        details.get("recipient_key"),
        details.get("recipient_email"),
        detected_accounts or [],
        entry_id or "none",
        details.get("error_type", "none"),
        details.get("error", message),
        details.get("hresult"),
        details.get("args"),
        exc_info=exc is not None,
    )
    return ToolResult(
        tool_name="outlook_create_summary_draft",
        ok=False,
        message=message,
        artifacts=[str(summary_path)] if summary_path else [],
        data=details,
        raw={
            "failure_stage": stage,
            "recipient_key": details.get("recipient_key"),
            "email_send_enabled": False,
            "approval_gated_email_send_enabled": True,
            "unrestricted_email_send_enabled": False,
            "sent": False,
        },
    )


def create_outlook_summary_draft(
    *,
    language: Literal["zh", "en"] = "zh",
    subject: str | None = None,
    recipient_key: str | None = None,
    display: bool = True,
) -> ToolResult:
    summary_path = latest_summary_path()
    sender_email = presentation_config.outlook_sender_email.strip()
    requested_recipient_key = recipient_key
    recipient: EmailRecipient | None = None
    stage = "recipient_file_lookup"
    detected_accounts: list[str] = []
    entry_id = ""

    try:
        recipient = presentation_config.resolve_recipient(requested_recipient_key)
        requested_recipient_key = recipient.key
    except (OSError, ValueError) as exc:
        return _failed_result(
            message=str(exc),
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=None,
            requested_recipient_key=requested_recipient_key,
            stage=stage,
            exc=exc,
        )

    recipient_email = recipient.email
    LOGGER.info(
        "OUTLOOK_DRAFT_START sender=%s recipient_key=%s recipient=%s summary=%s display=%s recipient_file=%s",
        sender_email,
        recipient.key,
        recipient_email,
        str(summary_path) if summary_path else "none",
        display,
        presentation_config.recipient_config_path,
    )

    if summary_path is None or not summary_path.is_file():
        return _failed_result(
            message="No generated presentation summary is available for the Outlook draft.",
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=recipient,
            requested_recipient_key=requested_recipient_key,
            stage="summary_lookup",
        )
    if not sender_email or not recipient_email:
        return _failed_result(
            message="Outlook sender and recipient email addresses must both be configured.",
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=recipient,
            requested_recipient_key=requested_recipient_key,
            stage="address_configuration",
        )
    if sender_email.casefold() == recipient_email.casefold():
        return _failed_result(
            message="Outlook sender and recipient must be different email addresses.",
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=recipient,
            requested_recipient_key=requested_recipient_key,
            stage="address_separation",
        )
    if os.name != "nt":
        return _failed_result(
            message="Classic Outlook COM automation is available only on Windows.",
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=recipient,
            requested_recipient_key=requested_recipient_key,
            stage="platform_check",
        )

    try:
        import pythoncom
        import win32com.client
    except ImportError as exc:
        return _failed_result(
            message="pywin32 is required for Classic Outlook draft creation.",
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=recipient,
            requested_recipient_key=requested_recipient_key,
            stage="dependency_import",
            exc=exc,
        )

    pythoncom.CoInitialize()
    try:
        stage = "outlook_connection"
        outlook, connection_mode = _outlook_application(win32com.client)
        namespace = outlook.GetNamespace("MAPI")

        stage = "sender_account_lookup"
        sender_account, detected_accounts = _find_sender_account(namespace, sender_email)
        summary_text = summary_path.read_text(encoding="utf-8")
        clean_subject = _clean_subject(subject, language)

        stage = "mail_item_creation"
        mail = outlook.CreateItem(OUTLOOK_MAIL_ITEM)

        stage = "sender_account_assignment"
        mail.SendUsingAccount = sender_account
        assigned_sender = _account_email(getattr(mail, "SendUsingAccount", None))
        if assigned_sender and assigned_sender.casefold() != sender_email.casefold():
            raise RuntimeError(
                f"Outlook bound the draft to {assigned_sender}, not configured sender {sender_email}."
            )

        stage = "recipient_resolution"
        outlook_recipient = mail.Recipients.Add(recipient_email)
        outlook_recipient.Type = OUTLOOK_TO_RECIPIENT
        if not bool(mail.Recipients.ResolveAll()):
            raise RuntimeError(
                f"Outlook could not resolve the configured recipient: {recipient_email}."
            )

        stage = "draft_save"
        mail.Subject = clean_subject
        mail.Body = _message_body(summary_text, language, recipient.name)
        mail.Save()
        entry_id = str(getattr(mail, "EntryID", "") or "")
        store_id = ""
        parent = getattr(mail, "Parent", None)
        if parent is not None:
            store_id = str(getattr(parent, "StoreID", "") or "")
        if not entry_id:
            raise RuntimeError("Outlook saved the draft but did not assign an EntryID.")

        stage = "draft_reopen_and_verify"
        saved = None
        saved_entry_id = ""
        saved_subject = ""
        saved_recipient_addresses: list[str] = []
        saved_sender = ""
        saved_state = False
        sent_state = False

        for _ in range(10):
            saved = (
                namespace.GetItemFromID(entry_id, store_id)
                if store_id
                else namespace.GetItemFromID(entry_id)
            )
            saved_entry_id = str(getattr(saved, "EntryID", "") or "")
            saved_subject = str(getattr(saved, "Subject", "") or "")
            saved_recipient_addresses = _recipient_smtp_addresses(saved)
            saved_sender = _account_email(getattr(saved, "SendUsingAccount", None))
            saved_state = bool(getattr(saved, "Saved", False))
            sent_state = bool(getattr(saved, "Sent", False))
            recipient_verified = [
                address.casefold() for address in saved_recipient_addresses
            ] == [recipient_email.casefold()]
            sender_verified = (
                (not assigned_sender or assigned_sender.casefold() == sender_email.casefold())
                and (not saved_sender or saved_sender.casefold() == sender_email.casefold())
            )
            if (
                saved_entry_id == entry_id
                and saved_subject == clean_subject
                and recipient_verified
                and sender_verified
                and saved_state
                and not sent_state
            ):
                break
            time.sleep(0.2)
        else:
            raise RuntimeError(
                "The Outlook draft was created but could not be verified. "
                f"Observed assigned_sender={assigned_sender or 'blank'}, "
                f"saved_sender={saved_sender or 'blank'}, "
                f"recipients={saved_recipient_addresses}, saved={saved_state}, sent={sent_state}."
            )

        displayed = False
        if display and saved is not None:
            stage = "draft_display"
            saved.Display(False)
            displayed = True

        relative_summary = _relative_or_absolute(summary_path)
        LOGGER.info(
            "OUTLOOK_DRAFT_SUCCESS sender=%s recipient_key=%s recipient=%s entry_id=%s store_id=%s connection_mode=%s detected_accounts=%s verified_recipients=%s displayed=%s recipient_file=%s",
            sender_email,
            recipient.key,
            recipient_email,
            entry_id,
            store_id or "none",
            connection_mode,
            detected_accounts,
            saved_recipient_addresses,
            displayed,
            presentation_config.recipient_config_path,
        )
        return ToolResult(
            tool_name="outlook_create_summary_draft",
            ok=True,
            message=(
                f"Outlook draft created from {sender_email} for {recipient.name} "
                f"<{recipient_email}>; it was not sent."
            ),
            expected_process_names=["OUTLOOK.EXE"],
            expected_window_keywords=[clean_subject, "Outlook"],
            artifacts=[str(summary_path)],
            data={
                "execution_mode": "real",
                "requested_state": {
                    "outlook_draft_created": True,
                    "recipient_key": recipient.key,
                },
                "outlook_draft_created": True,
                "outlook_draft_verified": True,
                "outlook_draft_entry_id": entry_id,
                "outlook_draft_store_id": store_id,
                "outlook_draft_displayed": displayed,
                "outlook_connection_mode": connection_mode,
                "sender_account_email": sender_email,
                "assigned_sender_account_email": assigned_sender or None,
                "saved_sender_account_email": saved_sender or None,
                "detected_outlook_accounts": detected_accounts,
                "recipient_key": recipient.key,
                "recipient_name": recipient.name,
                "recipient_email": recipient_email,
                "recipient_config_path": str(presentation_config.recipient_config_path),
                "verified_recipient_addresses": saved_recipient_addresses,
                "subject": clean_subject,
                "summary_path": str(summary_path),
                "summary_path_relative": relative_summary,
                "email_send_enabled": False,
                "approval_gated_email_send_enabled": True,
                "unrestricted_email_send_enabled": False,
                "sent": False,
            },
            raw={
                "outlook_draft_entry_id": entry_id,
                "outlook_draft_verified": True,
                "sender_account_email": sender_email,
                "recipient_key": recipient.key,
                "recipient_email": recipient_email,
                "verified_recipient_addresses": saved_recipient_addresses,
                "email_send_enabled": False,
                "approval_gated_email_send_enabled": True,
                "unrestricted_email_send_enabled": False,
                "sent": False,
            },
        )
    except Exception as exc:
        return _failed_result(
            message=f"Outlook draft could not be created: {type(exc).__name__}: {exc}",
            summary_path=summary_path,
            sender_email=sender_email,
            recipient=recipient,
            requested_recipient_key=requested_recipient_key,
            stage=stage,
            detected_accounts=detected_accounts,
            entry_id=entry_id,
            exc=exc,
        )
    finally:
        pythoncom.CoUninitialize()


def _relative_or_absolute(path: Path) -> str:
    from app.presentation_config import REPO_ROOT

    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path.resolve())
